import { API_BASE, BROWSER_ONLY } from './core/client.js';

export function mountAdmin(root) {
  let token = '', expiryTimer, panel = 'overview', offset = 0, selectedAccount = '', generation = 0;
  const english = document.documentElement.lang === 'en';
  const tr = (de, en) => english ? en : de;
  root.innerHTML = `<div class="admin-intro"><img src="${new URL('static/boosti.svg', new URL(document.querySelector('meta[name="app-base"]')?.content || './', location.href))}" alt="Boosty" width="56" height="60"><div><p class="eyebrow">BOOSTY AI · ADMIN</p><h1>${tr('Dein Überblick. Geschützt.', 'Your overview. Protected.')}</h1><p>${tr('Konten, Bewerbungen und Nutzung an einem Ort.', 'Accounts, applications and usage in one place.')}</p></div></div>
  <p class="admin-message" role="status" aria-live="polite"></p>
  <section class="admin-auth"><h2>${tr('Admin-Anmeldung', 'Admin sign-in')}</h2><p>${tr('Passwort und Authenticator-Code erforderlich. Die Sitzung endet nach 15 Minuten.', 'Password and authenticator code required. Sessions expire after 15 minutes.')}</p>
  <form class="admin-login"><label class="field">E-Mail<input name="email" type="email" autocomplete="username" maxlength="254" required></label><label class="field">${tr('Passwort', 'Password')}<input name="password" type="password" autocomplete="current-password" minlength="14" maxlength="128" required></label><label class="field">${tr('Authenticator-Code', 'Authenticator code')}<input name="code" inputmode="numeric" pattern="[0-9]{6}" autocomplete="one-time-code" maxlength="6" required></label><button class="button primary">${tr('Geschützt anmelden', 'Sign in securely')}</button></form>
  <details class="admin-setup"><summary>${tr('Ersteinrichtung mit privatem Einrichtungscode', 'First setup with private setup code')}</summary><p>${tr('Der Betreiber erstellt den Code auf dem Server. Öffentliche Registrierung vergibt keine Adminrechte.', 'The operator creates the code on the server. Public registration never grants administrator rights.')}</p><form class="admin-begin"><label class="field">E-Mail<input name="email" type="email" required maxlength="254" autocomplete="username"></label><label class="field">${tr('Einrichtungscode', 'Setup code')}<input name="setup_code" type="password" required autocomplete="off" maxlength="100"></label><button class="button outline">${tr('Authenticator verbinden', 'Connect authenticator')}</button></form>
  <form class="admin-finish" hidden><p>${tr('In deiner Authenticator-App einen zeitbasierten Eintrag (TOTP, SHA-1, 6 Ziffern, 30 Sekunden) für Boosty AI hinzufügen. Diesen Schlüssel manuell eintragen:', 'Add a time-based entry (TOTP, SHA-1, 6 digits, 30 seconds) for Boosty AI in your authenticator app. Enter this key manually:')}</p><code class="admin-secret"></code><label class="field">${tr('Eigenes Passwort (mindestens 14 Zeichen)', 'Your password (at least 14 characters)')}<input name="password" type="password" autocomplete="new-password" minlength="14" maxlength="128" required></label><label class="field">${tr('Aktueller Authenticator-Code', 'Current authenticator code')}<input name="code" inputmode="numeric" pattern="[0-9]{6}" autocomplete="one-time-code" required maxlength="6"></label><button class="button primary">${tr('Einrichtung abschließen', 'Complete setup')}</button></form></details></section>
  <section class="admin-dashboard" hidden><div class="admin-toolbar"><strong class="admin-email"></strong><span>${tr('Sitzung: höchstens 15 Minuten', 'Session: at most 15 minutes')}</span><button class="button outline admin-logout">${tr('Abmelden', 'Sign out')}</button></div><nav class="admin-nav" aria-label="Admin"><button data-view="overview">${tr('Übersicht', 'Overview')}</button><button data-view="users">${tr('Nutzer', 'Users')}</button><button data-view="sessions">${tr('Sitzungen', 'Sessions')}</button><button data-view="events">${tr('Nutzungsverlauf', 'Activity')}</button><button data-view="audit">${tr('Admin-Protokoll', 'Admin audit')}</button><button data-view="database">${tr('Datenbank', 'Database')}</button></nav><div class="admin-filter"><label class="field">${tr('Zeitraum', 'Period')}<select class="admin-days"><option value="7">7 ${tr('Tage', 'days')}</option><option value="30" selected>30 ${tr('Tage', 'days')}</option><option value="90">90 ${tr('Tage', 'days')}</option></select></label><label class="field admin-search-field">${tr('E-Mail suchen', 'Search email')}<input class="admin-search" type="search" maxlength="254"></label><button class="button outline admin-refresh">${tr('Aktualisieren', 'Refresh')}</button></div><div class="admin-content"></div><div class="admin-pagination"><button class="button quiet admin-prev">← ${tr('Zurück', 'Previous')}</button><span class="admin-page"></span><button class="button quiet admin-next">${tr('Weiter', 'Next')} →</button></div></section>`;
  const $ = s => root.querySelector(s), content = $('.admin-content');
  let setupCredentials;
  function clear() {
    generation++; token = ''; clearTimeout(expiryTimer);
    $('.admin-dashboard').hidden = true; $('.admin-auth').hidden = false;
    content.replaceChildren(); $('.admin-email').textContent = ''; $('.admin-secret').textContent = '';
    $('.admin-finish').hidden = true; setupCredentials = null;
    root.querySelectorAll('input[type="password"],input[name="code"]').forEach(e => e.value = '');
  }
  async function request(path, body) {
    const requestGeneration = generation;
    const response = await fetch(API_BASE + '/api/admin/' + path, { method: body ? 'POST' : 'GET', credentials: 'include', headers: {'X-Boosty-Request':'1', ...(body ? {'Content-Type':'application/json'} : {}), ...(token ? {Authorization:`Bearer ${token}`} : {})}, ...(body ? {body:JSON.stringify(body)} : {}), signal:AbortSignal.timeout(20000) });
    const data = await response.json();
    if (requestGeneration !== generation) throw new Error(tr('Admin-Sitzung beendet.', 'Admin session ended.'));
    if (!response.ok) { if ((response.status === 401 || response.status === 403) && !$('.admin-dashboard').hidden) clear(); throw new Error(typeof data.detail === 'string' ? data.detail : tr('Eingaben prüfen.', 'Check input.')); }
    return data;
  }
  const guarded = work => async e => { e?.preventDefault(); const buttons = [...root.querySelectorAll('button')]; buttons.forEach(b => b.disabled = true); $('.admin-message').textContent=''; try {await work(e);} catch(error){$('.admin-message').textContent=error.message;} finally {buttons.forEach(b => b.disabled=false);} };
  function label(text, element='p') { const el=document.createElement(element); el.textContent=text; return el; }
  function table(headers, rows) {const box=document.createElement('div'); box.className='admin-table-scroll'; const t=document.createElement('table'), h=document.createElement('tr');headers.forEach(x=>h.append(label(x,'th'))); const head=document.createElement('thead');head.append(h);t.append(head);const body=document.createElement('tbody');rows.forEach(values=>{const row=document.createElement('tr');values.forEach(v=>{const c=document.createElement('td');if(v instanceof Node)c.append(v);else c.textContent=v??'–';row.append(c);});body.append(row);});t.append(body);box.append(t);return box;}
  const date=v=>v?new Date(/(?:Z|[+-]\d\d:\d\d)$/.test(v)?v:v+'Z').toLocaleString(english?'en-GB':'de-DE'):'–';
  function button(text,work) {const b=label(text,'button');b.className='button quiet';b.addEventListener('click',guarded(work));return b;}
  function jsonView(title,data) {content.replaceChildren(label(title,'h2'));const p=document.createElement('pre');p.className='admin-record';p.textContent=JSON.stringify(data,null,2);content.append(p);$('.admin-pagination').hidden=true;}
  async function details(id) {selectedAccount=id; const value=await request('users/'+id);content.replaceChildren(label(value.email,'h2'),label(tr('Persönliche Inhalte nur für Supportzwecke öffnen. Jeder Zugriff wird protokolliert.', 'Open personal content only for support. Every access is audited.')));content.append(table(['ID',tr('Titel','Title'),'Status',tr('Aktion','Action')],value.applications.map(p=>[p.id,p.title,p.status,button(tr('Inhalt öffnen','Open content'),async()=>jsonView(p.title,(await request('applications/'+p.id)).data))])));content.append(label(tr('Sitzungen','Sessions'),'h3'),table(['ID',tr('Erstellt','Created'),tr('Aktion','Action')],value.sessions.map(s=>[s.id,date(s.created_at),button(tr('Sitzung ansehen','View session'),async()=>jsonView(s.id,await request('sessions/'+s.id)))])),button(tr('Nutzungsverlauf dieses Kontos','Activity for this account'),async()=>{panel='events';offset=0;await load();}));$('.admin-pagination').hidden=true;}
  async function load() {
    content.replaceChildren(); $('.admin-pagination').hidden=['overview','database'].includes(panel);$('.admin-search-field').hidden=panel!=='users';$('.admin-days').parentElement.hidden=panel!=='overview';
    root.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===panel)));
    const params=new URLSearchParams({offset,limit:25});let value;
    if(panel==='overview') {
      value=await request('overview?days='+$('.admin-days').value);const grid=document.createElement('div');grid.className='admin-metrics';const titles={accounts:tr('Registrierte Konten','Registered accounts'),new_accounts:tr('Neue Konten im Zeitraum','New accounts in period'),applications:tr('Gespeicherte Bewerbungen','Saved applications'),page_views:tr('Seitenaufrufe im Zeitraum','Page views in period'),visit_sessions:tr('Besuchssitzungen im Zeitraum','Visit sessions in period'),active_accounts:tr('Aktive Konten im Zeitraum','Active accounts in period')};Object.entries(titles).forEach(([k,title])=>{const card=document.createElement('article');card.append(label(String(value.totals[k]||0),'strong'),label(title));grid.append(card);});content.append(grid,label(tr(value.measurement,'Page views and started app sessions, not unique people. Bots, reloads and previews may be included. No IP tracking.')),table([tr('Tag (UTC)','Day (UTC)'),tr('Aufrufe','Views'),tr('Sitzungen','Sessions'),tr('Registrierungen','Registrations')],value.daily.map(v=>[v.day,v.page_views,v.visit_sessions,v.registrations])),label(tr('Verwendete Funktionen','Functions used'),'h3'),table([tr('Funktion','Function'),tr('Anzahl','Count')],value.operations.map(v=>[v.event,v.count])));return;
    }
    if(panel==='database'){value=await request('database');content.append(label(`${value.engine} · ${tr('Integrität','Integrity')}: ${value.integrity}`,'h2'),table([tr('Tabelle','Table'),tr('Datensätze','Records')],value.tables.map(v=>[v.name,v.rows])),label(tr(value.note,'Protected data views. Password hashes, keys and tokens are excluded. Complete backups require server CLI. No browser SQL editor.')));return;}
    if(panel==='users')params.set('q',$('.admin-search').value);
    if(panel==='events'&&selectedAccount)params.set('account_id',selectedAccount);
    value=await request(panel+'?'+params);
    if(panel==='users')content.append(table(['E-Mail',tr('Registriert','Registered'),tr('Zuletzt aktiv','Last active'),tr('Bewerbungen','Applications'),tr('Aktion','Action')],value.items.map(v=>[v.email,date(v.created_at),date(v.last_active_at),v.applications,button(tr('Details','Details'),()=>details(v.id))])));
    else if(panel==='sessions')content.append(table(['ID',tr('Konto-ID','Account ID'),tr('Erstellt','Created'),tr('Aktion','Action')],value.items.map(v=>[v.id,v.owner_id||tr('Anonym','Anonymous'),date(v.created_at),button(tr('Inhalte','Content'),async()=>jsonView(v.id,await request('sessions/'+v.id)))])));
    else content.append(table([tr('Zeit (UTC lokal angezeigt)','Time (UTC shown locally)'),tr('Konto','Account'),tr('Ereignis','Event'),panel==='audit'?tr('Ziel','Subject'):'HTTP'],value.items.map(v=>[date(v.created_at),v.email||tr('Anonym / unbekannt','Anonymous / unknown'),v.event||v.action,v.outcome??v.subject_id])));
    $('.admin-page').textContent=`${Math.min(offset+1,value.total)}–${Math.min(offset+25,value.total)} / ${value.total}`;
    $('.admin-prev').hidden=offset===0;$('.admin-next').hidden=offset+25>=value.total;
  }
  async function signedIn(value) {token=value.access_token||'';$('.admin-email').textContent=value.email;$('.admin-auth').hidden=true;$('.admin-dashboard').hidden=false;root.querySelectorAll('form').forEach(f=>f.reset());$('.admin-secret').textContent='';setupCredentials=null;clearTimeout(expiryTimer);expiryTimer=setTimeout(()=>{clear();$('.admin-message').textContent=tr('Sitzung abgelaufen. Bitte erneut anmelden.','Session expired. Sign in again.');},(value.expires_in||900)*1000);await load();}
  $('.admin-login').addEventListener('submit',guarded(async e=>signedIn(await request('login',Object.fromEntries(new FormData(e.target))))));
  $('.admin-begin').addEventListener('submit',guarded(async e=>{setupCredentials=Object.fromEntries(new FormData(e.target));const value=await request('setup/begin',setupCredentials);$('.admin-secret').textContent=value.secret;$('.admin-finish').hidden=false;}));
  $('.admin-finish').addEventListener('submit',guarded(async e=>signedIn(await request('setup/finish',{...setupCredentials,...Object.fromEntries(new FormData(e.target))}))));
  $('.admin-logout').addEventListener('click',guarded(async()=>{try{await request('logout',{});}finally{clear();}}));
  root.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',guarded(async()=>{panel=b.dataset.view;offset=0;selectedAccount='';await load();})));
  $('.admin-refresh').addEventListener('click',guarded(async()=>{offset=0;await load();}));$('.admin-prev').addEventListener('click',guarded(async()=>{offset=Math.max(0,offset-25);await load();}));$('.admin-next').addEventListener('click',guarded(async()=>{offset+=25;await load();}));
  $('.admin-days').addEventListener('change',guarded(load));
  if(BROWSER_ONLY){$('.admin-auth').hidden=true;$('.admin-message').textContent=tr('Der Adminbereich benötigt den App-Server.','Administration requires the app server.');}
  else request('me').then(signedIn).catch(()=>{});
  return {clear};
}
